name: dmdirect

on:
  schedule:
    - cron: '44 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "dmdirect bot"
      
      - name: grab m3u files
        run: python3 ressources/dmotion/py/dmdirect/dmdirect.py
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git commit -m "dmdirect updated"
          git push
