name: streamlinkfox

on:
  schedule:
    - cron: '02 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "streamlinkfox bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests streamlink

      - name: fetch content streamlinkfox
        run: |
          final_url=$(python3 ressources/tur/streamlinkfox.py)
          echo "final_url=${final_url}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          content="${{ env.final_url }}"
          sed -i "\|/foxtv/| c ${content}" all.m3u
          sed -i "\|/foxtv/| c ${content}" ressources/allgr.m3u

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add all.m3u ressources/allgr.m3u
          git commit -m "streamlinkfox updated"
          git push
